# Numpy
This is probably the most efficient library regarding scientific computation with arrays and matrices in Python. 
### Arrays (ndarrays)
The fundamental structure in Numpy is a data type called ndarrays (n-dimensional arrays). These structures are similar to Python's basic lists, but they offer advantages in terms of memory usage and data access.
### Importing Numpy
The instruction to import all contents of `numpy` is

In [2]:
import numpy as np # as np is the pseudonym

Now we play a bit with arrays.

In [3]:
# one dimensional array (vector)
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [4]:
# Operations with an array
print(a*4)
print(a+a)
print(a<3)
print(a**2)
print(a.T @ a) # np.dot(a,b)

[ 4  8 12 16 20]
[ 2  4  6  8 10]
[ True  True False False False]
[ 1  4  9 16 25]
55


In [5]:
sum(a**2)

np.int64(55)

In [8]:
a.shape

(5,)

And with 2-dimensional arrays, like 
$$b=\left(
    \begin{array}{c} 
    2 & 1 & 2\\\\
    1 & 4 & 1\\\\
    2 & 1 & 6
    \end{array} 
\right)$$

In [6]:
b=np.array([[2,1,2],[1,4,1],[2,1,6]])
print(b)
# Printing dimension, shape and size
print("Dimension: %i"%b.ndim)
print("Shape: "+str(b.shape))
print("Size: %i"%b.size)

[[2 1 2]
 [1 4 1]
 [2 1 6]]
Dimension: 2
Shape: (3, 3)
Size: 9


In [17]:
b[:,::2] ## a:b:c

array([[2, 2],
       [1, 1],
       [2, 6]])

We can reshape an array:

In [23]:
c = b.reshape(9)
c

array([2, 1, 2, 1, 4, 1, 2, 1, 6])

In [25]:
lista = [ii for ii in range(0, 11, 0.2)]
lista

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
my_array=np.arange(0.5,12.6,0.5)
print(my_array)

[ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5]


In [38]:
my_array[::-1]

array([12.5, 12. , 11.5, 11. , 10.5, 10. ,  9.5,  9. ,  8.5,  8. ,  7.5,
        7. ,  6.5,  6. ,  5.5,  5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,
        1.5,  1. ,  0.5])

In [27]:
my_array.shape

(25,)

In [28]:
print(my_array.reshape(5,5))

[[ 0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5. ]
 [ 5.5  6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5 10. ]
 [10.5 11.  11.5 12.  12.5]]


Now we index the elements of the array in different ways.

In [40]:
my_array = my_array.reshape(5,5)
# Elements of the first column
print(my_array[:,0])
# Elements of the first row
print(my_array[0,:])
# Diagonal elements
print(my_array.diagonal())
my_array

[ 0.5  3.   5.5  8.  10.5]
[0.5 1.  1.5 2.  2.5]
[ 0.5  3.5  6.5  9.5 12.5]


array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 5.5,  6. ,  6.5,  7. ,  7.5],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5]])

In [47]:
len(my_array)

5

In [53]:
np.zeros((4,3)).shape[1]

3

In [84]:
def minor(i,j, mat):
    rows = [ii for ii in range(len(mat))]
    columns = rows.copy()
    rows.remove(i); columns.remove(j)
    return mat[rows][:,columns]
    #var = mat[rows]
    #return var[:,columns]
my_array
print(minor(-1,-1,my_array))

[[ 0.5  1.   2.   2.5]
 [ 3.   3.5  4.5  5. ]
 [ 8.   8.5  9.5 10. ]
 [10.5 11.  12.  12.5]]


In [86]:
my_array[-1,-1]

np.float64(12.5)

In [73]:
obj=my_array[[0,1,3,4]]
obj

array([[ 0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ],
       [ 8. ,  8.5,  9. ,  9.5, 10. ],
       [10.5, 11. , 11.5, 12. , 12.5]])

In [74]:
obj[:,[0,1,3,4]]

array([[ 0.5,  1. ,  2. ,  2.5],
       [ 3. ,  3.5,  4.5,  5. ],
       [ 8. ,  8.5,  9.5, 10. ],
       [10.5, 11. , 12. , 12.5]])

In [66]:
minor(2,2, my_array)

[0, 1, 3, 4] [0, 1, 3, 4]


array([ 0.5,  3.5,  9.5, 12.5])

In [56]:
lista = [1,2,3,4]
print(lista.remove(2))

None


In [57]:
lista

[1, 3, 4]

### Random Arrays
`numpy` has dedicated methods to work with randon numbers. We will see some of them

In [102]:
# Printing (uniform) random numbers
# from 0 to 1, in a 10x10 matrix
random_numbers=np.random.random(size=(10,10)) 
print(random_numbers.shape)
# Select the ones smaller or equal to 0.5:
less_or_equal=random_numbers[random_numbers<=0.5]
print(less_or_equal)
print(less_or_equal.size)

(10, 10)
[0.04858696 0.10218501 0.16191658 0.30013725 0.44707151 0.112308
 0.40457038 0.23973569 0.17622336 0.34685063 0.01470069 0.02341875
 0.14697583 0.3228539  0.48174107 0.11519602 0.06952414 0.46058743
 0.36963597 0.12209463 0.31530804 0.328945   0.22967319 0.31308619
 0.42609997 0.39126115 0.10516061 0.32307304 0.05656214 0.30425778
 0.24715295 0.14344721 0.17442282 0.13311739 0.2842238  0.19607923
 0.15010889 0.13126795 0.10421217 0.04211582 0.02159897 0.4666462
 0.21462452 0.41937369 0.48008961 0.48940758 0.49340767 0.11438514
 0.32449051 0.44345469 0.4536359  0.35990661 0.44464133 0.25888862
 0.25467219]
55


In [100]:
help(np.random.random)

Help on method random in module numpy.random.mtrand:

random(size=None) method of numpy.random.mtrand.RandomState instance
    random(size=None)

    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [103]:
print(np.random.uniform(-5, 12, size=(5,5))) #(lower lim, upper lim, shape)
print()
print(np.random.normal(5, 5, size=(5,5))) #(mean, std, shape)

[[ 8.09487345 -1.3370044  -1.42956405 -1.35834531 10.52478115]
 [ 0.71477573  8.84172811 -3.87583398  6.09295125 -4.19797368]
 [ 5.43827958  2.00631414 11.44457809 -0.07663638 -0.40444423]
 [10.1173693   3.66196294 -0.78268875  8.84872724  7.37951447]
 [ 8.61342279  9.84247132 -2.87975392 -2.0606443   6.90654661]]

[[ 5.7060778  11.73167259  4.6370206   6.21562875  6.79310731]
 [ 6.08646249  1.55979719  2.36623319  1.93746692  5.92473641]
 [ 4.24190929 12.32454726  3.07888839  0.19756487  8.90999521]
 [13.80223728  3.95293209 -9.4400815   3.91305857  7.93105013]
 [-2.17550633  1.51376051  2.1620985  12.06135006 13.7399959 ]]


In [104]:
np.random.randint(0,10, size=(100,))

array([7, 3, 0, 6, 5, 4, 5, 0, 8, 4, 8, 6, 5, 7, 1, 1, 1, 7, 7, 8, 3, 2,
       2, 4, 6, 1, 8, 5, 2, 9, 3, 9, 0, 1, 5, 4, 4, 4, 8, 9, 9, 6, 4, 2,
       8, 7, 4, 4, 5, 9, 9, 8, 9, 7, 7, 2, 1, 9, 1, 1, 8, 1, 0, 5, 9, 3,
       3, 2, 5, 3, 0, 7, 7, 5, 5, 4, 1, 5, 3, 5, 5, 3, 7, 4, 4, 4, 4, 8,
       1, 8, 4, 1, 6, 0, 0, 2, 4, 8, 2, 5])

### Linear algebra
Now let us see some common linear algebra operations.

In [105]:
# a 3x3 matrix
matrix=np.array([[2,7,5],[0,9,8],[7,4,0]])
# Multiplying by the identity matrix
print(matrix.dot(np.eye(3,3)))

[[2. 7. 5.]
 [0. 9. 8.]
 [7. 4. 0.]]


In [109]:
matrix @ np.eye(2,3)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [111]:
# (Matrix)^2
print(matrix @ matrix,"\n", matrix ** 2)

[[ 39  97  66]
 [ 56 113  72]
 [ 14  85  67]] 
 [[ 4 49 25]
 [ 0 81 64]
 [49 16  0]]


In [112]:
# Matrix determinant
print(np.linalg.det(matrix))

13.000000000000005


### Intervals and Grids
Intervals have various applications, such as graphing or performing numerical integrations. Grids are two-dimensional intervals, useful when plotting three-dimensional surfaces. The methods for creating partitions are presented below.

The `meshgrid(a,b)` method creates a correspondence between all elements of a with all elements of b. This way, we create a two-dimensional surface, which is useful for graphing scalar fields of $F:\mathbb{R}^2\rightarrow \mathbb{R}$.

In [114]:
espacio = np.linspace(0,10,100)
print(espacio)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [119]:
x = np.array([1,2,3])
y = np.array([4,5,6,7])
X,Y = np.meshgrid(x,y)
print(X)
print()
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]


### Solve a system of linear equations
Is easy to solve linear equation systems with **Numpy**, one can initialize the two matrices $A$ and $b$ that satisfies $Ax=b$ for an unique value of $x$. Notice that if the system is inconsistent or linearly dependent, **Numpy** will throw an error. Let's see some examples.

Suposse you want to solve the next linear equation system:

$$\left(
    \begin{array}{c} 
    3 & 1\\
    1 & 2 
    \end{array} 
\right)
\left(
    \begin{array}{c}
    x_1\\
    x_2
    \end{array}
\right)=
\left(
    \begin{array}{c}
    9\\
    8
    \end{array}
\right)$$
This is the way to do it.

In [120]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

[2. 3.]


or

In [121]:
print(np.dot(np.linalg.inv(a),b))

[2. 3.]


### Eigenvalues and eigenvectors
Recall that an eigenvalue $\lambda$ (with resp. eigenvector $v$) of a matrix $A$ satisfies $$Av = \lambda v$. We can find the eigenvalues and eigenvectors of a given matrix using numpy.

In [122]:
w, v = np.linalg.eig(np.diag((1, 2, 3)))
print(w) #Where w is an array with the eigenvalues
print(v) #And v is a matrix with the eigenvectors

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Examples
1. Using numpy arrays, show all odd numbers between 1 and 3000.

In [127]:
a = np.arange(1, 3001)
a[a%2 == 1]

array([   1,    3,    5, ..., 2995, 2997, 2999])

2. Roll six six-sided dice many times. Numerically, what is the probability that two or more dice show the same number? If you roll seven six-sided dice, what is the probability that at least two of them show the same number?

_ 5/6 4/6 3/6 2/6 1/6 = $\frac{6!}{6^6}$
Probability to obtain at least two equal dice: 1-6!/6^6 

In [181]:
dice = np.random.randint(1,7, size=(1000000, 6))
dice.sort()
arr = np.array([1,2,3,4,5,6])
1-np.sum(np.sum(dice == arr, axis=1) == 6)/len(dice)

np.float64(0.984438)

In [182]:
import math
1-math.factorial(6)/6**6

0.9845679012345679

In [151]:
dice.sort(axis=0)

In [152]:
dice

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 2, 2, 1, 1],
       [1, 1, 2, 2, 1, 2],
       [1, 1, 2, 2, 1, 2],
       [2, 1, 2, 2, 1, 2],
       [2, 2, 2, 2, 1, 2],
       [2, 2, 2, 2, 1, 2],
       [2, 2, 2, 2, 1, 2],
       [2, 2, 2, 2, 1, 2],
       [2, 2, 2, 2, 1, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 2, 3, 3, 2, 2],
       [3, 3, 3, 3, 2, 2],
 

In [130]:
np.unique(np.array([1,2,3,4,4,5,5,6]))

array([1, 2, 3, 4, 5, 6])

3. Compute the dot product between two one-dimensional arrays of numbers.

In [ ]:
a.T @ b

4. Separate the perfect squares of the array
```python
a=np.array([4,5,7,49,34,36,21,16,101,121,169,100,82,33,81,64])
```

In [2]:
import numpy as np

In [22]:
a=np.array([4,5,7,49,34,36,21,16,101,121,169,100,82,33,81,64])
mask = ((a**0.5) % 1 == 0) | (a%2==0)

In [23]:
a[mask]

array([  4,  49,  34,  36,  16, 121, 169, 100,  82,  81,  64])

In [24]:
np.floor(a**0.5)

array([ 2.,  2.,  2.,  7.,  5.,  6.,  4.,  4., 10., 11., 13., 10.,  9.,
        5.,  9.,  8.])